name: CI Pipeline

on:
  push:
    branches:
      - test  # Only runs on the 'test' branch
  pull_request:
    branches:
      - test  # Runs on PRs to the 'test' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Fix Jest permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Run tests
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: npx jest --runInBand
