name: CI Pipeline

on:
  push:
    branches:
      - test  # Only runs on the 'test' branch
  pull_request:
    branches:
      - test  # Runs on PRs to the 'test' branch

jobs:
  frontend:
    name: Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Node.js
        uses: actions/setup-node@v3  # Updated to v3
        with:
          node-version: '18'  # Use Node.js 18 as required

      - name: Install dependencies
        run: npm install

      - name: Fix Jest permissions
        run: chmod +x ./node_modules/.bin/jest

      - name: Run frontend tests
        env:
          NODE_OPTIONS: '--max-old-space-size=4096'
        run: npx jest --runInBand

  backend:
    name: Backend Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3  # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4  # Updated to v4
        with:
          python-version: '3.8'

      - name: Install Python dependencies
        run: pip install -r backend/requirements.txt

      - name: Run Python tests individually
        run: |
          for test_file in $(ls backend/tests/*.py); do
            echo "Running test: $test_file"
            pytest $test_file || exit 1
          done

